//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:10:39 AM PDT 
//


package com.yourcompany;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EventGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VenueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Town" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TicketCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SwURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EventGroupImageURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LayoutId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EventGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="VenueId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SwSellURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "date",
    "eventGroupName",
    "venueName",
    "town",
    "country",
    "ticketCount",
    "currency",
    "minPrice",
    "swURL",
    "eventGroupImageURL",
    "layoutId",
    "eventGroupId",
    "venueId",
    "swSellURL"
})
public class Event {

    @XmlElement(name = "Id")
    protected int id;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "EventGroupName", required = true)
    protected String eventGroupName;
    @XmlElement(name = "VenueName", required = true)
    protected String venueName;
    @XmlElement(name = "Town", required = true)
    protected String town;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "TicketCount")
    protected int ticketCount;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "MinPrice", required = true)
    protected BigDecimal minPrice;
    @XmlElement(name = "SwURL", required = true)
    protected String swURL;
    @XmlElement(name = "EventGroupImageURL", required = true)
    protected String eventGroupImageURL;
    @XmlElement(name = "LayoutId")
    protected int layoutId;
    @XmlElement(name = "EventGroupId")
    protected int eventGroupId;
    @XmlElement(name = "VenueId")
    protected int venueId;
    @XmlElement(name = "SwSellURL", required = true)
    protected String swSellURL;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the eventGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventGroupName() {
        return eventGroupName;
    }

    /**
     * Sets the value of the eventGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventGroupName(String value) {
        this.eventGroupName = value;
    }

    /**
     * Gets the value of the venueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenueName() {
        return venueName;
    }

    /**
     * Sets the value of the venueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenueName(String value) {
        this.venueName = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the ticketCount property.
     * 
     */
    public int getTicketCount() {
        return ticketCount;
    }

    /**
     * Sets the value of the ticketCount property.
     * 
     */
    public void setTicketCount(int value) {
        this.ticketCount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the minPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * Sets the value of the minPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinPrice(BigDecimal value) {
        this.minPrice = value;
    }

    /**
     * Gets the value of the swURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwURL() {
        return swURL;
    }

    /**
     * Sets the value of the swURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwURL(String value) {
        this.swURL = value;
    }

    /**
     * Gets the value of the eventGroupImageURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventGroupImageURL() {
        return eventGroupImageURL;
    }

    /**
     * Sets the value of the eventGroupImageURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventGroupImageURL(String value) {
        this.eventGroupImageURL = value;
    }

    /**
     * Gets the value of the layoutId property.
     * 
     */
    public int getLayoutId() {
        return layoutId;
    }

    /**
     * Sets the value of the layoutId property.
     * 
     */
    public void setLayoutId(int value) {
        this.layoutId = value;
    }

    /**
     * Gets the value of the eventGroupId property.
     * 
     */
    public int getEventGroupId() {
        return eventGroupId;
    }

    /**
     * Sets the value of the eventGroupId property.
     * 
     */
    public void setEventGroupId(int value) {
        this.eventGroupId = value;
    }

    /**
     * Gets the value of the venueId property.
     * 
     */
    public int getVenueId() {
        return venueId;
    }

    /**
     * Sets the value of the venueId property.
     * 
     */
    public void setVenueId(int value) {
        this.venueId = value;
    }

    /**
     * Gets the value of the swSellURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwSellURL() {
        return swSellURL;
    }

    /**
     * Sets the value of the swSellURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwSellURL(String value) {
        this.swSellURL = value;
    }

}
