//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:10:39 AM PDT 
//


package com.yourcompany;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PageNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PageResultCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalResultCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalPageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pageNumber",
    "pageSize",
    "pageResultCount",
    "totalResultCount",
    "totalPageCount"
})
public class Paging {

    @XmlElement(name = "PageNumber")
    protected int pageNumber;
    @XmlElement(name = "PageSize")
    protected int pageSize;
    @XmlElement(name = "PageResultCount")
    protected int pageResultCount;
    @XmlElement(name = "TotalResultCount")
    protected int totalResultCount;
    @XmlElement(name = "TotalPageCount")
    protected int totalPageCount;

    /**
     * Gets the value of the pageNumber property.
     * 
     */
    public int getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     */
    public void setPageNumber(int value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     */
    public void setPageSize(int value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the pageResultCount property.
     * 
     */
    public int getPageResultCount() {
        return pageResultCount;
    }

    /**
     * Sets the value of the pageResultCount property.
     * 
     */
    public void setPageResultCount(int value) {
        this.pageResultCount = value;
    }

    /**
     * Gets the value of the totalResultCount property.
     * 
     */
    public int getTotalResultCount() {
        return totalResultCount;
    }

    /**
     * Sets the value of the totalResultCount property.
     * 
     */
    public void setTotalResultCount(int value) {
        this.totalResultCount = value;
    }

    /**
     * Gets the value of the totalPageCount property.
     * 
     */
    public int getTotalPageCount() {
        return totalPageCount;
    }

    /**
     * Sets the value of the totalPageCount property.
     * 
     */
    public void setTotalPageCount(int value) {
        this.totalPageCount = value;
    }

}
